### PR TITLE
Calendar pointing

### PR DESCRIPTION
**Pull request by emersonlaurentino**
**What kind of change does this PR introduce?**
#1

**What is the current behavior?**
#1

**What is the new behavior?**
The portal can be formatted so that is pointing.

**Checklist**:

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by arthurdenner** [comment]
Thanks, @emersonlaurentino! I'll try to review it on the weekend. Meanwhile, if you are interested, could you try to support `top left` and `top right` in this `pointing` prop? I think it would be a nice feature.

**Comment by emersonlaurentino** [comment]
Yes, I'll try to do that.

**Comment by emersonlaurentino** [comment]
@arthurdenner I added the support for pointing `top` `top left` `top right` `bottom` `bottom left` `bottom right` `right` `left`.

**Comment by arthurdenner** [comment]
Nice! I noticed that some of these are a little redundant. Can we stick with `left`, `right` (both render on bottom), `top left` and `top right`?

**Pull request merged**
