### PR TITLE
added missing pointing prop definition

### PR DESCRIPTION
**Pull request by jaaaco**
related to #32

### CODE REVIEW

**Comment by arthurdenner** [comment]
Hi @jaaaco! Thanks for interest in contributing to the library.

Could you please open another PR with the Polish locale instead of adding it with this one?

I'd like to keep different features in different PRs to a better changelog.

Thanks again!

**Comment by jaaaco** [comment]
@arthurdenner Done :)

**Comment by arthurdenner** [comment]
Thanks @jaaaco!

Sorry for the wait to merge it, I've been very busy lately.

Your fix is live in the version `1.10.1` of the library. :tada:

**Pull request merged**
